### PR TITLE
Add a link to drive gears with the correct dimensions

### PR DESCRIPTION
**Pull request by momorox**

### CODE REVIEW

**Comment by cjbaar** [comment]
Thanks for the update on the gears! Have you tried these? I guess I hesitate to use Ebay as a link source because it could change easily, right?

**Comment by momorox** [comment]
I installed them but have not yet tried them. I'll update you on how they function once I do.

I agree with you, however I was unable to find any permanent source that sells ones with the correct dimensions. I bought from 5 different people on Amazon and other websites and they all had a height of 11mm even though they were advertised as being 12mm. This is the only one I found that is actually 12mmx12mmx5mm.

**Comment by cjbaar** [comment]
Yeah; I ordered two different batches that were 11mm. They *may* work, but because of the way I have the alignment, every other filament resets right on that edge. So I'm not sure what could happen with a small gap there.

**Comment by momorox** [comment]
Looks like it's sold out and they aren't restocking it. You might wanna revert it.

**Comment by jasonmatthews41** [comment]
I built mine with the 11mm gears. I was able to make sure that none of the set screws or gaps were in line with any filaments. I've been running it for weeks now, flawlessly. I think the 11mm ones are going to be fine.

**Comment by momorox** [comment]
That's great. You mind posting a picture of your gears orientation?

**Comment by jasonmatthews41** [comment]
As you see, some of them end up actually on the gaps between the gears. My setup has been running just fine.

**Comment by jasonmatthews41** [comment]
And actually, I stand corrected. Two of my filament paths, are actually over set screws. It still works just fine regardless.

**Comment by jasonmatthews41** [comment]
Also, while I'm on the subject... I designed and developed my own sealed, dry buffer system for 12 filaments.

It's kind of a bad angle, I have a very cramped setup behind my printer. I had to tilt the entire assembly askew, to have everything feed on all 12 colors in the fluid sense. I've been running this for at least a dozen prints for a week solid. I have no problems.

**Comment by momorox** [comment]
That's cool. I guess the real question is whether or not flexible filaments will work for the two filaments paths that are over set screws.

**Comment by jasonmatthews41** [comment]
That is something I have not tried. I have only tested PLA on this system. I can only assume that TPU would probably jam up on the set screws. I never even thought about that. I was only thinking multicolor. I'm doing an entire other MMU setup for my Prusa core 1 when it arrives. That one will be doing multiple engineering materials, not so much colors.

**Comment by HonzaJaros** [comment]
Can you let us know how the firmware from printer is properly passed or not to the mmu since Prusa made the printer the flashing device for the mmu?Honza On 31 Dec 2024, at 12:58 pm, Jason Matthews ***@***.***> wrote:﻿
That is something I have not tried. I have only tested PLA on this system. I can only assume that TPU would probably jam up on the set screws. I never even thought about that. I was only thinking multicolor. I'm doing an entire other MMU setup for my Prusa core 1 when it arrives. That one will be doing multiple engineering materials, not so much colors.

**Comment by jasonmatthews41** [comment]
@HonzaJaros, I used cjbaar's provided firmware for the MMU12. Also, Prusa is also providing the exact same firmware to flash to the MMU3/MMU12. I have found that either firmware flashes work very well with the Prusa MK4S. It equally works well for the Prusa MK4. I have only had one potentially troublesome print, and that's because my PLA was wet.

**Comment by ErwanMAS** [comment]
@jasonmatthews41 do you plan to share your 12 slot buffer  ?
github printables or thingiverse ?

**Pull request merged**
